### ISSUE TITLE
[Feature] Support for reusable workflow documentation

### ISSUE THREAD

**Issue by andreas-aman** [tj-actions/auto-doc#404]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

We have reusable workflow where we manually create documentation for inputs and secrets.

### Describe the solution you'd like?

Would be great if this action also could support extracting documentation from reusable workflows.

### Describe alternatives you've considered?

I've considered making a separate action for handling this scenario but it would mean duplication of code.

### Anything else?

I'd be happy to help with updating the code to support reusable workflows.
But first you'll have to agree it's a good use case and then decide how the action should determine whether it's an action or a reusable workflow it should create documentation for.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ViacheslavKudinov** [comment]
Agreed, will be good to get this feature if possible.

**Comment by andreas-aman** [comment]
I took a look at the code and have a suggestion. It would be a breaking change simply because the inputs to this action would have to change. When you have time feel free to take a look. If you think it's somewhat OK I can open a PR.

https://github.com/andreas-aman/auto-doc/tree/reusable

**Comment by jackton1** [comment]
@andreas-aman Sure, I’ll be happy to review the PR

**Comment by cbrett692** [comment]
I'm looking forward to this feature! 
Thanks for implementing @andreas-aman 😃

**Comment by jackton1** [comment]
@cbrett692 @ViacheslavKudinov @major0 This should now be available in the latest release,

**Comment by RotemBirman** [comment]
@jackton1 I'm trying to use this feature in v2.2.4 and although me readme.md is empty and I have around 10 gha action listed I'm not getting any changes.
auto-dec is reporting on "Successfully generated documentation" and "verify-changed-files" is saying "No changes found"
this is my GHA job - 
```
jobs:
  update-doc:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0

        - name: Run auto-doc
          uses: tj-actions/auto-doc@v2.2.4
          with:
            reusable: true

        - name: Verify Changed files
          uses: tj-actions/verify-changed-files@v14
          id: verify-changed-files
          with:
            files: |
              README.md
```
And this is my action.yml
```
name: README.md
description: create README.md
runs:
  using: composite
  steps:
    - uses: ./.github/actions/file1.yaml
    - uses: ./.github/actions/file2.yaml
    - uses: ./.github/actions/file3.yaml
    - uses: ./.github/actions/file4.yaml
    - uses: ./.github/actions/file5.yaml
    - uses: ./.github/actions/file6.yaml
    - uses: ./.github/actions/file7.yaml
```
