### ISSUE TITLE
[Feat]: Add placeholder and indicate when headers are used without any corresponding data.

### ISSUE THREAD

**Issue by looztra** [tj-actions/auto-doc#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When the action does not have any inputs, the placeholders are removed from the markdown files when the expected behaviour is to keep them

```md
## Inputs

<!-- AUTO-DOC-INPUT:START - Do not remove or modify this section -->
<!-- AUTO-DOC-INPUT:END -->
```

### To Reproduce

With this action:

```yaml
name: Action without input
description: Action without input

runs:
  using: "composite"
  steps:
    - name: Noop
      shell: bash
      run: |
        date
```

And this content of the README.md

```md
## Inputs

<!-- AUTO-DOC-INPUT:START - Do not remove or modify this section -->
<!-- AUTO-DOC-INPUT:END -->
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The README.md should stay the same:

```md
## Inputs

<!-- AUTO-DOC-INPUT:START - Do not remove or modify this section -->
<!-- AUTO-DOC-INPUT:END -->
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
