### ISSUE TITLE
Syntax for reusable_output_columns?

### ISSUE THREAD

**Issue by enderm** [tj-actions/auto-doc#496]
Having a hard time figuring out the syntax for reusable_output_columns in the yaml format:

I cannot use a list:

```yaml
      - name: Run auto-doc for base.yaml
        uses: tj-actions/auto-doc@v2
        with:
          reusable: true
          filename: .github/workflows/base.yaml
          output: docs/base.md
          reusable_output_columns: 
             - Output
             - Description
```
fails with 
```
The workflow is not valid. .github/workflows/autodoc.yaml (Line: 28, Col: 14): A sequence was not expected
```

And not multiple paramaters either, like in the cli:

```yaml
      - name: Run auto-doc for base.yaml
        uses: tj-actions/auto-doc@v2
        with:
          reusable: true
          filename: .github/workflows/base.yaml
          output: docs/base.md
          reusable_output_columns: Output
          reusable_output_columns: Description
```

That fails with:

```
The workflow is not valid. .github/workflows/autodoc.yaml (Line: 28, Col: 11): 'reusable_output_columns' is already defined
```

What is the correct syntax, please?

**Comment by jackton1** [comment]
You need to use a multiline string

```yml
      - name: Run auto-doc for base.yaml
        uses: tj-actions/auto-doc@v2
        with:
          reusable: true
          filename: .github/workflows/base.yaml
          output: docs/base.md
          reusable_output_columns: |
            Output
            Description
```

For more information on writing YAML syntax see: https://learnxinyminutes.com/docs/yaml/
