### ISSUE TITLE
[Feature] REQUIRED parameters at the top of the generated docs

### ISSUE THREAD

**Issue by z15alall** [tj-actions/auto-doc#546]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Currently Input are listed in alphanumeric order

### Describe the solution you'd like?

For our point of view it's better to have requiered parameters on the top of documentation. It's more easy for our customer to see what is required like that, insteat of searching all required parameters.  Our actions parameters are contruct to that order.

i think it will be great to have an option to perserve order parameters in action to the generated doc instead of order by alphanumeric value.

```
name: "myAction"
description: "myAction"
inputs:
  b_inputs:
    description: "Inputs B required"
    required: true

  c_inputs:
    description: "Inputs C required"
    required: true

  a_inputs:
    description: "Inputs A non required"
    required: false
```

with actual version docs will be : 
a_inputs | not required
b_inputs | required
c_inputs | required 

with this new feature, order will be preserve : 
b_inputs | required
c_inputs | required
a_inputs  | not required

### Describe alternatives you've considered?

Need to change manually this order of parameters to have required parameter on the top of the doc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
